---

  - hosts: all
    sudo: true

    tasks:

      - name: update apt
        apt: update_cache=yes

      - name: Install packages (might take a while)
        apt: name={{item}} state=present
        with_items:
          - texlive
          - biber
          - texlive-lang-german
          - texlive-latex-extra

      - name: Copy bashrc
        template:
          src=bashrc
          dest=/home/vagrant/.bashrc
